# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad4115b4a6af98345409df1e3529be5bc493922eb27da029521889085d3a0d2e8f5b058993fd61e6a682c32f179b09564ea842dd16573473c9f936111a155edc

test:
  secret_key_base: 9354fd60f8f938fe53d11c62a07646f6109c7bdd44c198ffa6fc37aab53820a155be49fc4a2581347d3a9c15998a3a61304c6080ab529d80d5c80b9469fbdfe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
